### ISSUE TITLE
Missing Parameter on the getPages method

### ISSUE THREAD

**Issue by mikeapr4** [agility/agility-sync-sdk#17]
As per the readme, the API here is intended to match the [Content Fetch API](https://github.com/agility/agility-content-fetch-js-sdk), however, we've found we cannot pass `expandAllContentLinks` to the getPage method ([docs](https://agilitydocs.netlify.app/agility-content-fetch-js-sdk/1.1.1/agilityfetch.client.pages#.getPage)). Can this be added?

**Comment by joelvarty** [comment]
Hi there - we haven't put this into the Sync API at this point.  In general, I recommend making separate calls for linked lists, especially from pages.

**Comment by mikeapr4** [comment]
Ok, understood 👍
